## Ejercicios pair programming 01 diciembre: Numpy I

Ejercicio 1: Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota

El array de 2 dimensiones debe ser de 2 filas y 3 columnas
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [1]:
import numpy as np    #importamos la libreria para poder trabajar con numpy

In [9]:
lista1 = [23,213,53,24]   #para el primer array usaremos una lista para crear el array
array1= np.array(lista1)
array1

array([ 23, 213,  53,  24])

In [10]:
array2 = np.random.randint(0,100, (2,3))  #para el segundo array usaremos el metodo random.randint
array2


array([[67, 82,  3],
       [90, 33, 14]])

In [11]:
array3 = np.random.rand(2,3,5)  #para el tercer array usaremos random entre 0 y 1
array3


array([[[0.77940541, 0.60883768, 0.56230964, 0.95078194, 0.56414798],
        [0.21534585, 0.36178689, 0.61647364, 0.80110524, 0.30295165],
        [0.68078458, 0.79458018, 0.49755018, 0.97055107, 0.55289818]],

       [[0.046657  , 0.20242292, 0.4737093 , 0.96959788, 0.06337076],
        [0.0726083 , 0.27215752, 0.35451886, 0.17125681, 0.2093337 ],
        [0.97011762, 0.22147151, 0.00568107, 0.4482927 , 0.287842  ]]])

Ejercicio 2: Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [14]:
def chequear_array(array):
    print(f"La dimension del array {array} es: {array.ndim}")  #aqui nos printea la dimension del array
    print(f"El tipo del array {array} es: {array.dtype}")   #aqui nos printea el tipo del array
    print(f"El tamaño del array {array} es: {array.size}")  #aqui nos printea el tamaño del array
    print(f"La forma del array {array} es: {array.shape}")  #aqui nos printea la forma del array

In [15]:
chequear_array(array1)

La dimension del array [ 23 213  53  24] es: 1
El tipo del array [ 23 213  53  24] es: int64
El tamaño del array [ 23 213  53  24] es: 4
La forma del array [ 23 213  53  24] es: (4,)


In [16]:
chequear_array(array2)

La dimension del array [[67 82  3]
 [90 33 14]] es: 2
El tipo del array [[67 82  3]
 [90 33 14]] es: int64
El tamaño del array [[67 82  3]
 [90 33 14]] es: 6
La forma del array [[67 82  3]
 [90 33 14]] es: (2, 3)


In [17]:
chequear_array(array3)

La dimension del array [[[0.77940541 0.60883768 0.56230964 0.95078194 0.56414798]
  [0.21534585 0.36178689 0.61647364 0.80110524 0.30295165]
  [0.68078458 0.79458018 0.49755018 0.97055107 0.55289818]]

 [[0.046657   0.20242292 0.4737093  0.96959788 0.06337076]
  [0.0726083  0.27215752 0.35451886 0.17125681 0.2093337 ]
  [0.97011762 0.22147151 0.00568107 0.4482927  0.287842  ]]] es: 3
El tipo del array [[[0.77940541 0.60883768 0.56230964 0.95078194 0.56414798]
  [0.21534585 0.36178689 0.61647364 0.80110524 0.30295165]
  [0.68078458 0.79458018 0.49755018 0.97055107 0.55289818]]

 [[0.046657   0.20242292 0.4737093  0.96959788 0.06337076]
  [0.0726083  0.27215752 0.35451886 0.17125681 0.2093337 ]
  [0.97011762 0.22147151 0.00568107 0.4482927  0.287842  ]]] es: float64
El tamaño del array [[[0.77940541 0.60883768 0.56230964 0.95078194 0.56414798]
  [0.21534585 0.36178689 0.61647364 0.80110524 0.30295165]
  [0.68078458 0.79458018 0.49755018 0.97055107 0.55289818]]

 [[0.046657   0.20242292 0

Ejercicio 3: Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [19]:
array4= np.identity(3)   #creamos la matriz identidad con el metodo identity
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Ejercicio 4: Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [20]:
array5 = np.ones_like(array3)   #creamos la nueva array con el metodo ones_like copiando la alterior
array5

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

Ejercicio 5: Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [21]:
#Sumar array 
array6 = array2 + array4 
#nos da error porque tienen diferente forma, una dos filas y la otra tres

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [22]:
#la solucion seria crear un array nuevo de 3 dimensiones
array7 = np.identity(3)
array8 = array7 + array4
array8


array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [26]:
np.add(array7,array4)   #usamos el metodo de numpy para sumar arrays

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [23]:
#multiplicamos las array
array9 = array8 * array4
array9

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [27]:
np.multiply(array8,array4)  #usamos el metodo de numpy para multiplicar array

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [24]:
#dividimos las array
array10 = array8 / array4
array10

/var/folders/lb/nyps7wf17_767t6ln21znwmh0000gn/T/ipykernel_27152/2467989799.py:2: RuntimeWarning: invalid value encountered in true_divide
  array10 = array8 / array4


array([[ 2., nan, nan],
       [nan,  2., nan],
       [nan, nan,  2.]])

In [28]:
np.divide(array8,array4)   #usamos el metodo de numpy para dividir array

/var/folders/lb/nyps7wf17_767t6ln21znwmh0000gn/T/ipykernel_27152/914797327.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(array8,array4)


array([[ 2., nan, nan],
       [nan,  2., nan],
       [nan, nan,  2.]])